export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS1: "SET_PRODUCTS1",
  SET_PRODUCTS2: "SET_PRODUCTS2",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  CLEAR_PRODUCT:"CLEAR_PRODUCT",
  SET_BUNCHES:"SET_BUNCHES",
  SET_BUNCHES_COMING:"SET_BUNCHES_COMING",
  SET_BUNCHES_LATEST:"SET_BUNCHES_LATEST",
};
